[package]
name = "ldbucket"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
indicatif = "0.18.0"
rand = "0.9.1"
rand_distr = "0.5.1"
rayon = "1.10.0"
rust-htslib = "0.49.0"
